# Generated by Django 3.2 on 2023-04-26 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('contnent', models.TextField(max_length=5000, verbose_name='content')),
                ('active', models.BooleanField(default=False)),
            ],
        ),
    ]
